### ISSUE TITLE
Type piracy

### ISSUE THREAD

**Issue by odow** [trulsf/UnitJuMP.jl#19]
This method is type piracy:

https://github.com/trulsf/UnitJuMP.jl/blob/c55366ff1c4f090105aa50ec7d6285368b5c7bed/src/units.jl#L178-L181

The tests fail with `JuMP#master` because we now return a `VectorNonlinearFunction` instead of hitting this method.

I don't know what a good solution is. Perhaps we just don't support multi-objective problems with UnitJuMP for now?

**Comment by trulsf** [comment]
The type piracy arised when trying to support multiobjective optmization combining objectives with and without units. My suggestion is to support only multiobjective optimization when all objectives have units. This should not be too much of a restriction. See pull request #20

**Comment by trulsf** [comment]
Fixed in version 0.2.2
